### ISSUE TITLE
Bug: Failed Decryption

### ISSUE THREAD

**Issue by malvidin** [CybercentreCanada/assemblyline-service-peepdf#17]
An old sample of an encrypted PDF delivered by email was not decrypted successfully when the password was in the email body, or when provided manually.  The decrypted PDF was not visible in DocumentPreview, but the PDF only contained an extortion message and a Bitcoin address when manually opened.

**Comment by cccs-rs** [comment]
Should be resolved in the Extract service (v4.2.0.stable30). PDFId has been updated to ignore password protected PDFs since it doesn't yield any useful information but PeePDF will still accept them.
